platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

workspace 'DZNEmptyDataSet.xcworkspace'

target 'Applications' do
    pod 'SnapKit'
end

target 'DZNEmptyDataSetTests' do
    pod 'iOSSnapshotTestCase'
    pod 'SnapKit'
end
