platform :ios, '12.4'

use_frameworks!
inhibit_all_warnings!

workspace 'DZNEmptyDataSet.xcworkspace'

target 'DZNEmptyDataSetTests' do
    project 'DZNEmptyDataSet.xcodeproj'

    pod 'iOSSnapshotTestCase'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Forces all pods to be configured against Swift 4.0
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
